name: 'Terraform Github Actions'
on:
  pull_request:
    push:
      branches:
       - terraform/ResourceGroup 
jobs:
  terraform:
    name: 'Terraform init'
    runs-on: windows
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Terraform initialization"
        uses: hashicorp/terraform_github_actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand:  "init"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
  shelljob:
    name: "Demo"
    runs-on: windows
    steps:
     - name: "Shell Demo"
       run: curl www.googl.com
       shell: bash
